import { BiodataFormData, initialBiodata } from "@/types/biodata";

/**
 * One worked example per landing page.
 *
 * Every value here is fictional — invented names, `example.com` addresses and
 * masked phone numbers. These are rendered verbatim into a public page, so a
 * real person's contact details must never appear in this file.
 *
 * Four distinct samples rather than one reused four times, and that is the
 * point rather than an indulgence: four pages showing the same document with a
 * different heading is a doorway-page pattern. Each of these shows what its own
 * case actually looks like — a Hindu biodata carries গোত্র and রাশি, a Muslim
 * one carries মাসলাক, and neither ever shows the other's fields.
 */
const base = initialBiodata;

export const patriSample: BiodataFormData = {
  meta: { candidateKind: "bride", documentLanguage: "bn" },
  personal: {
    ...base.personal,
    fullName: "সুমাইয়া রহমান (উদাহরণ)",
    birthPlace: "সিলেট, বাংলাদেশ",
    dateOfBirth: "2001-06-14",
    age: "25",
    height: "5 ft 3 in (160 cm)",
    weight: "52 kg",
    bodyType: "Slim",
    complexion: "Fair",
    bloodGroup: "B+",
    religion: "Islam",
    motherTongue: "Bengali",
    maritalStatus: "Never Married",
    nationality: "Bangladeshi",
    hometown: "সিলেট, বাংলাদেশ",
    healthNotes: "কোনো শারীরিক জটিলতা নেই",
  },
  religious: {
    ...base.religious,
    maslak: "সুন্নি (হানাফি)",
    prayerRegularity: "পাঁচ ওয়াক্ত",
    observance: "হিজাব পরিধান করেন",
  },
  education: {
    ...base.education,
    graduation: "বি.এ (সম্মান) – ইংরেজি সাহিত্য",
    graduationInstitution: "উদাহরণ মহিলা কলেজ, সিলেট",
    graduationYear: "2023",
    graduationResult: "CGPA 3.68 / 4.00",
    hsc: "এইচ.এস.সি – মানবিক",
    hscInstitution: "উদাহরণ সরকারি কলেজ, সিলেট",
    hscYear: "2019",
    hscResult: "GPA 5.00",
    school: "এস.এস.সি – মানবিক",
    schoolName: "উদাহরণ বালিকা উচ্চ বিদ্যালয়",
    schoolYear: "2017",
    schoolResult: "GPA 4.89",
    designation: "সহকারী শিক্ষক",
    company: "উদাহরণ কিন্ডারগার্টেন",
    employmentType: "বেসরকারি",
    workLocation: "সিলেট",
  },
  family: {
    ...base.family,
    fatherName: "মিজানুর রহমান",
    fatherOccupation: "ব্যবসায়ী",
    fatherStatus: "জীবিত",
    motherName: "নাসরিন আক্তার",
    motherOccupation: "গৃহিণী",
    motherStatus: "জীবিত",
    brothersCount: "1",
    sistersCount: "0",
    siblingsNote: "এক বড় ভাই, বিবাহিত, প্রকৌশলী",
    familyType: "যৌথ পরিবার, মধ্যবিত্ত",
    familyValues: "ধর্মীয় ও রক্ষণশীল",
    economicStatus: "সচ্ছল",
    nativePlace: "বিয়ানীবাজার, সিলেট",
  },
  address: {
    presentAddress: "বাসা ০০, রোড ০০, উদাহরণ এলাকা, সিলেট – 3100",
    permanentAddress: "বিয়ানীবাজার, সিলেট, বাংলাদেশ",
  },
  contact: {
    ...base.contact,
    contactPerson: "মিজানুর রহমান",
    contactRelation: "পিতা",
    phone: "+880 1XXXXXXXXX",
    email: "guardian@example.com",
  },
  lifestyle: {
    ...base.lifestyle,
    hobbies: "বই পড়া, রান্না",
    languages: "বাংলা, ইংরেজি",
    personality: "শান্ত, দায়িত্বশীল",
    diet: "সাধারণ (হালাল)",
  },
  partner: {
    ...base.partner,
    ageRange: "26 – 32 বছর",
    education: "স্নাতক বা তদূর্ধ্ব",
    profession: "যেকোনো স্থায়ী পেশা",
    religion: "ইসলাম",
    maritalStatus: "অবিবাহিত",
    location: "সিলেট বিভাগ অগ্রাধিকার",
  },
};

export const patroSample: BiodataFormData = {
  meta: { candidateKind: "groom", documentLanguage: "bn" },
  personal: {
    ...base.personal,
    fullName: "আরিফুল ইসলাম (উদাহরণ)",
    birthPlace: "রাজশাহী, বাংলাদেশ",
    dateOfBirth: "1995-11-02",
    age: "30",
    height: "5 ft 9 in (175 cm)",
    weight: "72 kg",
    bodyType: "Average",
    complexion: "Brown",
    bloodGroup: "A+",
    religion: "Islam",
    motherTongue: "Bengali",
    maritalStatus: "Never Married",
    nationality: "Bangladeshi",
    hometown: "ঢাকা, বাংলাদেশ",
    healthNotes: "সুস্থ",
  },
  religious: {
    ...base.religious,
    maslak: "সুন্নি (হানাফি)",
    prayerRegularity: "পাঁচ ওয়াক্ত",
  },
  education: {
    ...base.education,
    masters: "এম.বি.এ – ফাইন্যান্স",
    mastersInstitution: "উদাহরণ বিশ্ববিদ্যালয়, ঢাকা",
    mastersYear: "2021",
    mastersResult: "CGPA 3.55 / 4.00",
    graduation: "বি.বি.এ – হিসাববিজ্ঞান",
    graduationInstitution: "উদাহরণ বিশ্ববিদ্যালয়, ঢাকা",
    graduationYear: "2018",
    graduationResult: "CGPA 3.48 / 4.00",
    hsc: "এইচ.এস.সি – ব্যবসায় শিক্ষা",
    hscInstitution: "উদাহরণ কলেজ, রাজশাহী",
    hscYear: "2013",
    hscResult: "GPA 4.90",
    designation: "সিনিয়র অফিসার",
    company: "উদাহরণ ব্যাংক পিএলসি",
    employmentType: "বেসরকারি চাকরি",
    workLocation: "ঢাকা",
    monthlyIncome: "৳85,000",
    experience: "7 বছর",
    domain: "রিটেইল ব্যাংকিং",
  },
  family: {
    ...base.family,
    fatherName: "সাইফুল ইসলাম",
    fatherOccupation: "অবসরপ্রাপ্ত শিক্ষক",
    fatherStatus: "জীবিত",
    motherName: "রোকেয়া বেগম",
    motherOccupation: "গৃহিণী",
    motherStatus: "জীবিত",
    brothersCount: "0",
    sistersCount: "2",
    siblingsNote: "দুই বোন, উভয়েই বিবাহিত",
    familyType: "একক পরিবার, উচ্চ-মধ্যবিত্ত",
    familyValues: "ধর্মীয় ও আধুনিক",
    economicStatus: "সচ্ছল",
    nativePlace: "পবা, রাজশাহী",
    property: "ঢাকায় নিজস্ব ফ্ল্যাট",
  },
  address: {
    presentAddress: "বাসা ০০, রোড ০০, উদাহরণ এলাকা, ঢাকা – 1207",
    permanentAddress: "পবা, রাজশাহী, বাংলাদেশ",
  },
  contact: {
    ...base.contact,
    contactPerson: "সাইফুল ইসলাম",
    contactRelation: "পিতা",
    phone: "+880 1XXXXXXXXX",
    whatsapp: "+880 1XXXXXXXXX",
    email: "guardian@example.com",
  },
  lifestyle: {
    ...base.lifestyle,
    hobbies: "ভ্রমণ, ক্রিকেট",
    languages: "বাংলা, ইংরেজি, হিন্দি",
    personality: "সৎ, ধৈর্যশীল",
    diet: "সাধারণ (হালাল)",
    smoking: "না",
  },
  partner: {
    ...base.partner,
    ageRange: "22 – 27 বছর",
    heightRange: "5'1\" – 5'5\"",
    education: "স্নাতক",
    working: "বাধ্যতামূলক নয়",
    religion: "ইসলাম",
    maritalStatus: "অবিবাহিত",
    familyType: "যেকোনো",
    location: "ঢাকা অগ্রাধিকার",
  },
};

export const muslimSample: BiodataFormData = {
  ...patroSample,
  meta: { candidateKind: "unspecified", documentLanguage: "bn" },
  personal: {
    ...patroSample.personal,
    fullName: "মোহাম্মদ তানভীর হাসান (উদাহরণ)",
    birthPlace: "কুমিল্লা, বাংলাদেশ",
    dateOfBirth: "1996-04-19",
    age: "30",
    hometown: "কুমিল্লা, বাংলাদেশ",
  },
  religious: {
    ...base.religious,
    maslak: "সুন্নি (হানাফি)",
    prayerRegularity: "পাঁচ ওয়াক্ত জামাতে",
    observance: "দাড়ি রাখেন, রমজানে নিয়মিত রোজা",
  },
  contact: {
    ...patroSample.contact,
    contactPerson: "আব্দুল হাসান",
    contactRelation: "পিতা",
  },
};

export const hinduSample: BiodataFormData = {
  meta: { candidateKind: "unspecified", documentLanguage: "bn" },
  personal: {
    ...base.personal,
    fullName: "অর্ণব চক্রবর্তী (উদাহরণ)",
    birthPlace: "খুলনা, বাংলাদেশ",
    dateOfBirth: "1994-09-27",
    /* Time of birth is not optional decoration on a Hindu biodata — it is what
       a কোষ্ঠী মিলান is calculated from. */
    timeOfBirth: "04:25",
    age: "31",
    height: "5 ft 10 in (178 cm)",
    weight: "70 kg",
    bodyType: "Average",
    complexion: "Fair",
    bloodGroup: "O+",
    religion: "Hinduism",
    motherTongue: "Bengali",
    maritalStatus: "Never Married",
    nationality: "Bangladeshi",
    hometown: "খুলনা, বাংলাদেশ",
  },
  religious: {
    ...base.religious,
    caste: "ব্রাহ্মণ",
    subCaste: "রাঢ়ী",
    gotra: "কাশ্যপ",
    rashi: "তুলা",
    nakshatra: "স্বাতী",
    manglik: "না",
  },
  education: {
    ...base.education,
    masters: "এম.এস.সি – পদার্থবিজ্ঞান",
    mastersInstitution: "উদাহরণ বিশ্ববিদ্যালয়, খুলনা",
    mastersYear: "2019",
    mastersResult: "CGPA 3.72 / 4.00",
    graduation: "বি.এস.সি – পদার্থবিজ্ঞান",
    graduationInstitution: "উদাহরণ বিশ্ববিদ্যালয়, খুলনা",
    graduationYear: "2017",
    graduationResult: "CGPA 3.65 / 4.00",
    designation: "প্রভাষক",
    company: "উদাহরণ সরকারি কলেজ",
    employmentType: "সরকারি চাকরি",
    workLocation: "খুলনা",
    monthlyIncome: "৳60,000",
    experience: "5 বছর",
  },
  family: {
    ...base.family,
    fatherName: "সুব্রত চক্রবর্তী",
    fatherOccupation: "অবসরপ্রাপ্ত ব্যাংক কর্মকর্তা",
    fatherStatus: "জীবিত",
    motherName: "মিতা চক্রবর্তী",
    motherOccupation: "গৃহিণী",
    motherStatus: "জীবিত",
    brothersCount: "0",
    sistersCount: "1",
    siblingsNote: "এক ছোট বোন, শিক্ষার্থী",
    familyType: "একক পরিবার, মধ্যবিত্ত",
    familyValues: "সনাতনী ও শিক্ষানুরাগী",
    economicStatus: "সচ্ছল",
    nativePlace: "ডুমুরিয়া, খুলনা",
  },
  address: {
    presentAddress: "বাসা ০০, রোড ০০, উদাহরণ এলাকা, খুলনা – 9100",
    permanentAddress: "ডুমুরিয়া, খুলনা, বাংলাদেশ",
  },
  contact: {
    ...base.contact,
    contactPerson: "সুব্রত চক্রবর্তী",
    contactRelation: "পিতা",
    phone: "+880 1XXXXXXXXX",
    email: "guardian@example.com",
  },
  lifestyle: {
    ...base.lifestyle,
    hobbies: "সংগীত, দাবা",
    languages: "বাংলা, ইংরেজি",
    personality: "শান্ত, পরিশ্রমী",
    diet: "নিরামিষ",
    smoking: "না",
    drinking: "না",
  },
  partner: {
    ...base.partner,
    ageRange: "24 – 29 বছর",
    education: "স্নাতক বা তদূর্ধ্ব",
    religion: "হিন্দু",
    maritalStatus: "অবিবাহিত",
    diet: "নিরামিষ অগ্রাধিকার",
    location: "খুলনা বা ঢাকা",
  },
};
